In [11]:
import pandas as pd


In [12]:
df =pd.read_csv("townhousePrice.csv")

In [14]:
df.columns

Index(['town', 'area', 'price'], dtype='object')

In [16]:
dummies=pd.get_dummies(df.town)
dummies

manmore township  robbinsville  west windsor
0               True         False         False
1               True         False         False
2               True         False         False
3               True         False         False
4               True         False         False
5              False         False          True
6              False         False          True
7              False         False          True
8              False         False          True
9              False          True         False
10             False          True         False
11             False          True         False
12             False          True         False

In [78]:
merged=pd.concat([df, dummies], axis='columns')
merged

town  area   price  manmore township  robbinsville  west windsor
0      0  2600  550000              True         False         False
1      0  3000  565000              True         False         False
2      0  3200  610000              True         False         False
3      0  3600  680000              True         False         False
4      0  4000  725000              True         False         False
5      2  2600  585000             False         False          True
6      2  2800  615000             False         False          True
7      2  3300  650000             False         False          True
8      2  3600  710000             False         False          True
9      1  2600  575000             False          True         False
10     1  2900  600000             False          True         False
11     1  3100  620000             False          True         False
12     1  3600  695000             False          True         False

In [79]:
final=merged.drop(['town', 'west windsor'],axis='columns')
final

area   price  manmore township  robbinsville
0   2600  550000              True         False
1   3000  565000              True         False
2   3200  610000              True         False
3   3600  680000              True         False
4   4000  725000              True         False
5   2600  585000             False         False
6   2800  615000             False         False
7   3300  650000             False         False
8   3600  710000             False         False
9   2600  575000             False          True
10  2900  600000             False          True
11  3100  620000             False          True
12  3600  695000             False          True

In [80]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [81]:
X=final.drop('price',axis='columns')
X

area  manmore township  robbinsville
0   2600              True         False
1   3000              True         False
2   3200              True         False
3   3600              True         False
4   4000              True         False
5   2600             False         False
6   2800             False         False
7   3300             False         False
8   3600             False         False
9   2600             False          True
10  2900             False          True
11  3100             False          True
12  3600             False          True

In [82]:
y=final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [83]:
model.fit(X,y)

LinearRegression()

In [84]:
model.predict([[2800,0,1]])

/Users/pranayspeed/miniconda3/envs/dev/lib/python3.10/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [85]:
model.predict([[3400,0,0]])

/Users/pranayspeed/miniconda3/envs/dev/lib/python3.10/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [86]:
model.score(X,y)

0.9573929037221873

In [88]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [89]:
dfle=df
dfle.town=le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [180]:
X=dfle[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [181]:
y=dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [182]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [183]:
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [188]:
X_new = ohe.fit_transform(X[:,0].reshape(-1,1)).toarray()

In [189]:
import numpy as np

In [190]:
X.shape, X_new.shape


((13, 2), (13, 3))

In [195]:
X1 = np.concatenate([X_new[:,1:], X[:,1:]], axis=1)
X1

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [197]:
model.fit(X1,y)

LinearRegression()

In [198]:
model.predict([[1,0, 2800]])

array([590775.63964739])

In [199]:
model.predict([[0, 1, 3400]])

array([681241.6684584])